### ISSUE TITLE
FiTaskフォルダの階層

### ISSUE THREAD

**Issue by yuki2825624** [rarula/FiTask#9]
新しいTaskを作成したときにFiTaskフォルダが生成される階層が、VSCodeで開いているフォルダの一番上の階層に生成されてしまい、階層を変えてしまうとTaskが読み込まれなくなってしまいます。
Taskを作成しているファイルと同じ階層の時だけ読み取れる、もしくはTaskを作成しているファイルによってFiTaskフォルダの階層を指定するなどは出来ないでしょうか？

**Comment by rarula** [comment]
問題の報告と提案ありがとうございます。

「開いているプロジェクトの階層を変更しても、その中で既にタスクが割り当てられていたファイルに関してはタスクの参照を続けたい」という認識でよろしいでしょうか？

**Comment by yuki2825624** [comment]
ご返事ありがとうございます。
そういう事です。説明足らずで申し訳ありません。
もう少し詳しく言えば、「FiTaskフォルダの階層を変更しても割り当てられているファイルのタスクの参照が出来る」という感じです。
勿論どちらも出来れば一番有難いです。

**Comment by rarula** [comment]
FiTaskフォルダの階層を、プロジェクトのルートディレクトリから「foo/bar/FiTask」の場所に移動したとき、
settings.jsonに以下の設定を追加するとタスクの参照を続けることが出来ますが、これで解決する問題でしょうか？

```json
{
  "fiTask.taskDirectory": "foo/bar/FiTask"
}
```

（何が起こっていて何が問題なのかが詳しく理解できていないので、的外れな回答をしていたら申し訳ないです）

**Comment by yuki2825624** [comment]
すいません返事遅れました。
解決しました！ありがとうございます
